### ISSUE TITLE
Should I use cookstyle for inspec profiles as well?

### ISSUE THREAD

**Issue by mhedgpeth** [chef/cookstyle#26]
Would you like to support sane inspec profile linting or should we create specstyle?

**Comment by adamleff** [comment]
Agree with @schisamo that another style library is probably overkill here. If someone were to ask my opinion on it, given that we support users shipping InSpec profiles and standalone controls in cookbooks, I'd encourage them to use `cookstyle.`

**Comment by mhedgpeth** [comment]
Great, I'm just making sure this is the right direction. I've heard people doing pretty well with cookstyle. I'll raise any issues as they come up.

**Comment by lamont-granquist** [comment]
Yeah, I would tend to suggest not using chefstyle, since that is probably "crossing the streams" and would result in much unhappiness.  If there's rubocop rules in cookstyle which don't apply well to inspec rules, its more likely that cookstyle should get changed to be more compatible.  I can't imagine there would be a rule where cookbook-recipe-code-authors would want it one way, but inspec-rule-authors would want it a different way.  However, stranger things that what I've imagined were possible have happened -- still this can probably be addressed by rubocop's path-specificity if it does ever come up.
