### ISSUE TITLE
[Enhancement] A single config file to use with vanilla rubocop

### ISSUE THREAD

**Issue by americanhanko** [chef/cookstyle#39]
I'm using RubyMine as my IDE. There is a Rubcop plugin that looks for `.rubocop.yml` by default, so I just put the content of `cookstyle.yml` into a `.rubocop.yml` file. However, the rules don't seem to match up with the results of running `cookstyle` against the same cookbook. 

I'm not super familiar with how `rubocop` works, but I imagine there would be a way to get all the active rules into `cookstyle.yml`? I don't really understand the relationship between all of the files in `config/`.

**Edit:** It turns out that looking at source code makes sense. I see this now in `config/default.yml`:
```yml
inherit_from:
  - upstream.yml
  - disable_all.yml
  - cookstyle_base.yml
  - cookstyle.yml
```

Still, it would be nice to a single config have a file that vanilla `rubocop` can use without all of the inheritance that yields the same result as running `cookstyle`

```
$ curl https://raw.githubusercontent.com/chef/cookstyle/master/config/cookstyle.yml > .rubocop.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3265  100  3265    0     0  29487      0 --:--:-- --:--:-- --:--:-- 34010
$ which rubocop; rubocop --version
/opt/chefdk/embedded/bin/rubocop
0.49.1
$ rubocop --config .rubocop.yml
Inspecting 24 files
......W..W.........C...C

[various offenses are shown here]

24 files inspected, 6 offenses detected
$ which cookstyle; cookstyle --version
/opt/chefdk/bin/cookstyle
Cookstyle 2.1.0
  * RuboCop 0.49.1
$ cookstyle
Inspecting 24 files
........................

24 files inspected, no offenses detected
```

**Comment by americanhanko** [comment]
Closing the issue until I figure out what I'm doing.

**Comment by americanhanko** [comment]
Updating the cops in `cookstyle_default.yml` resolves the issue and matches `cookstyle` behavior:

```
$ rubocop --config default.yml
Inspecting 24 files
........................

24 files inspected, no offenses detected
```

**Comment by lamont-granquist** [comment]
you have to be running exactly the same version of rubocop as is pinned in cookstyle or else you'll get differing results.  the debug output you got indicates that you probably had a different version of rubocop.  the pinning of the engine is a feature of cookstyle since every new version of rubocop is essentially a breaking change and they don't and probably can't usefully follow semver (as they fix bugs, you'll tend to get more failures even if they kept the ruleset exactly identical -- so every new rubocop release always 'breaks' CI testing -- hence half the purpose of this repo is to equality pin the rubocop engine to a single version across all of the chef cookbooks).

you'd most likely be better off modifying the plugin to run cookstyle instead of rubocop.

**Comment by americanhanko** [comment]
>the debug output you got indicates that you probably had a different version of rubocop.

I was actually using version `0.49.1` for both. Maybe that means `cookstyle_default.yml` is due for an update? Once I modified that file, it worked. 

>you'd most likely be better off modifying the plugin to run cookstyle instead of rubocop.

Indeed this is the best solution. At this point, RubyMine is due for a `cookstyle` plugin anyway.
