### ISSUE TITLE
parentheses in the method call but there is no method call

### ISSUE THREAD

**Issue by rlewkowicz** [chef/cookstyle#6]
So I have a cron resource:

```ruby
cron 'psquery upload' do
  action node.tags.include?('psquery-upload') || node['wp_onewise']['dirty_said_cron']['psquery-upload'] ? :create : :delete
  minute '0'
  hour '23'
  user 'root'
  command "#{gdriveroot}/Gdriveuploader/query.bash"
end
```

Which works, but cookstyle is like "Use parentheses in the method call to avoid confusion about precedence. "

If I had to guess, it's saying that I'm using all sorts of operators and to avoid and concerns I should group them explicitly. Easy enough

```ruby
action (node.tags.include?('psquery-upload') || node['wp_onewise']['dirty_said_cron']['psquery-upload']) ? :create : :delete
```

rspec is still happy, but cookstyle is now unhappy about this:

interpreted as grouped expression.

cookstyle --version 
Cookstyle 0.0.1
  * RuboCop 0.39.0

cat /opt/chefdk/version-manifest.txt 
chefdk 0.18.30

**Comment by lamont-granquist** [comment]
Thanks for filing a GitHub Issue. 

At Chef, we use GitHub Issues to track bugs and feature requests. Questions like "How do I .... with Chef?" are better answered by our awesome community on the Chef mailing lists, or on StackOverflow. (Please pick only one place to ask your question, however, as it's considered impolite to post the same question to multiple forums.)

You can find information about joining and asking questions on our mailing lists [here](https://github.com/opscode/chef/blob/master/CONTRIBUTING.md#chef-community). On StackOverflow, please tag your question with the "chef" label so that it shows up in [this list](https://stackoverflow.com/questions/tagged/chef).

We will be closing your issue. Please get in touch with the community via the above mechanisms in order to find a solution to your problem.

**Comment by rlewkowicz** [comment]
Is this an auto response? There's something fundamentally wrong with the way cookstyle is interpreting my code. I can resolve the error just fine. I set 'node.tags.include?('psquery-upload') || node['wp_onewise']['dirty_said_cron']['psquery-upload'] ? :create : :delete' to a variable and cook style was fine with it. If you look, I'm not calling a method. Unless you want to call a resource a method.  It's almost as if cook style is trying to evaluate the underlying resource provider. The response from cookstyle to what I am doing is not relevant to anything so far as I can tell. This looks like a bug.
