### ISSUE TITLE
Strange style issue with %w

### ISSUE THREAD

**Issue by aspyatkin** [chef/cookstyle#836]
# Version:
7.8.3

# Environment:
RuboCop 1.10.0

# Scenario:

Linting a cookbook reports a style issue with %w-literal, suggesting changing `%w[]` to `%w()`, which contradicts https://rubystyle.guide#percent-literal-braces

# Steps to Reproduce:

create a sample cookbook (`chef generate cookbook test`) with the following code to default recipe

```
pkg_names = %w[libpcre3 libpcre3-dev zlib1g zlib1g-dev]
```

# Expected Result:

No style issues

# Actual Result:

default.rb:6:13: C: [Correctable] Style/PercentLiteralDelimiters: %w-literals should be delimited by ( and ). (https://rubystyle.guide#percent-literal-braces)
pkg_names = %w[libpcre3 libpcre3-dev zlib1g zlib1g-dev]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by Muriel-Salvan** [comment]
Same issue with `%i`: it suggests to change `[ ]` into `( )`, which is against Rubystyle.

**Comment by tas50** [comment]
The RuboCop style doc has evolved over time and Cookstyle is not going to track every one of those changes. If we changed it to match RuboCop every time they updated the style guide we'd break CI pipelines for most customers, which isn't a reasonable thing to do. The Cookstyle style guide is always going to differ a bit from what RuboCop has chosen.

**Comment by aspyatkin** [comment]
It is unclear then how a user could obtain any knowledge about "correct" percent-literal braces, since it is not mentioned in Chef docs at all.

**Comment by Tensibai** [comment]
No need to be snarky neither (and I say that while being super vocal about the SLA in community slack). 

Back on topic: using parentheses has been standard ruby for while (after being brackets before and the change was welcome) and when you have CI systems going around some files to update them, handling only parentheses which are super common everywhere and an easy spot to take care of sounds a better 'norm' IMHO.

Square brakes are super heavy to escape when you drop Jenkins in the flow due to how Java may interpret them, bash has many other way to interpret them depending on context too...

Well all in all, I don't get rubocop upstream choice  and would prefer the chef norm to stuck with parentheses.

**Comment by chuhn** [comment]
Hm, the error message refers to [the Ruby style guide](https://rubystyle.guide#percent-literal-braces) and the explanation there makes `cookstyle` look a little like an idiot:
```ruby
# bad
%w(one two three)
…
# good
%w[one two three]
```
It would be nice to fix that link – and maybe point it to this issue here.

This style change was [introduced in 2016](https://github.com/rubocop/ruby-style-guide/issues/526) – before the first release of cookstyle btw.
Will cookstyle eventually return to standard Ruby style (maybe in 2026)?
Or will cookstyle stick to the Ruby coding standards of the last decade forever?
